language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - cd install
  - if [ "$CXX" == "g++" ]; then chmod +x ./install-gcc.sh; fi
  - if [ "$CXX" == "g++" ]; then sudo -E ./install-gcc.sh; fi
  - if [ "$CXX" == "clang++" ]; then chmod +x ./install-clang.sh; fi
  - if [ "$CXX" == "clang++" ]; then sudo -E ./install-clang.sh; fi
  - cd ..

script:
  - cd src
  - qmake collisions.pro
  - make
